/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_planet_light2345_seclib_SecService */

#ifndef _Included_com_planet_light2345_seclib_SecService
#define _Included_com_planet_light2345_seclib_SecService

// a加密key 对应版本号： 1
//#define SALT "401094610planettwo2345qxxk"

#define NORMAL_KEY "mpwy0rhfkc75h7yu"
//签名
#define SIGNATURE "308202dd308201c5a00302010202047a048020300d06092a864886f70d01010b0500301e310d300b060355040b130432333435310d300b06035504031304323334353020170d3138303730353036313030355a180f32303638303632323036313030355a301e310d300b060355040b130432333435310d300b060355040313043233343530820122300d06092a864886f70d01010105000382010f003082010a0282010100ba1105df7ce8add7a489e765a67b4983be131cb0908f48a25a77100f9572fc31b002de5b802363988cfef41cad39c3a80bb33b3a3b11add112ab68ec1dee1ef5df383551bb011f2a9cb4b3a104b8da9968a355e19f31d4a0882a4c330b5a8516b9b25d9d78c1460fbf4ab5d636549199e16a64ab243c9897b04fbd6d8a8a1ff49d603b72cebcb6c22a0a8d718d26e9cfa5861082ed8b10a3d855b0c4dea5e27b7fef117c102c3e528013ce7604f5e993b08fe16ee0779d7c262e0521f18f7910c407cf2d6d5f864155467b7b8b0fa64349ae8beae2d65c9da220762fd37218471f66719538e5b5ece41a384d8f7a86f00dace08dab83fa2e6f52350aa74b75cb0203010001a321301f301d0603551d0e04160414df3ea8f66dc7c656be7c1a0a51ff62b1588e4199300d06092a864886f70d01010b050003820101007973b333a875c69ade2db29c44d1ccf6a3c0ed70456a9d04812fc5194336e17f3ba7d96232a204d3c46026f223ee9f8465b9c35bf183c8248105bdd09216975dfd7b7b4d0e2d715da05b7dbcd24c0aa4377db2fb5b3c3fb0d46321123e5d3963a96579cf4028fba5ea310be6f0feb359c63f2537ed9ea12972924039d7c4ab2f2b67f6da214356385a74526cda1082b6236b293980d843fecc63a4ebb7829020e7746fc1a6f321ed9ef69ebcd1a84628467d7b2e770928f55bd78b2ba75df7887a9cac3f1223a7b4c04d4c122a3bbe0c467cc97fce3f0611fdcb3dd6b402cecc566c48093d8ab4535601870bb53c9f67e063eb636625feb6c8f83a75e11e5de8"

#define DEBUG 0
#define TAG "MHttpNative"


#if DEBUG
#include <android/log.h>
#define V(x...) __android_log_print(ANDROID_LOG_VERBOSE, TAG, x)
#define I(x...) __android_log_print(ANDROID_LOG_INFO, TAG, x)
#define D(x...) __android_log_print(ANDROID_LOG_DEBUG, TAG, x)
#define W(x...) __android_log_print(ANDROID_LOG_WARN, TAG, x)
#define E(x...) __android_log_print(ANDROID_LOG_ERROR, TAG, x)
#else
#define V(...) do{} while(0)
#define I(...) do{} while(0)
#define D(...) do{} while(0)
#define W(...) do{} while(0)
#define E(...) do{} while(0)
#endif

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_planet_light2345_seclib_SecService
 * Method:    encryptIn
 * Description: 加密，输入content，NORMAL_KEY作为key，再和内容一起加密
 * Signature: (Landroid/content/Context;[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_planet_light2345_seclib_SecService_encryptIn
    (JNIEnv *, jclass, jobject, jbyteArray);

/*
 * Class:     com_planet_light2345_seclib_SecService
 * Method:    decryptIn
 * Description: 解密，输入content，NORMAL_KEY作为key，再和内容一起解密
 * Signature: (Landroid/content/Context;[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_planet_light2345_seclib_SecService_decryptIn
    (JNIEnv *, jclass, jobject, jbyteArray);

/*
 * Class:     com_planet_light2345_seclib_SecService
 * Method:    encryptP1
 * Description: 加密，输入content、p1，p1作为key，再和内容一起加密
 * Signature: (Landroid/content/Context;[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_planet_light2345_seclib_SecService_encryptP1
    (JNIEnv *, jclass, jobject, jbyteArray, jbyteArray);

/*
 * Class:     com_planet_light2345_seclib_SecService
 * Method:    decryptP1
 * Description: 解密，输入content、p1，p1作为key，再和内容一起解密
 * Signature: (Landroid/content/Context;[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_planet_light2345_seclib_SecService_decryptP1
    (JNIEnv *, jclass, jobject, jbyteArray, jbyteArray);

/*
 * Class:     com_planet_light2345_seclib_SecService
 * Method:    encrypt2
 * Description: 加密，输入content、key参数1、key参数2，p1 + normalKey + p2作为key，md5后作为key，再和内容一起加密
 * Signature: (Landroid/content/Context;[B[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_planet_light2345_seclib_SecService_encrypt2
    (JNIEnv *, jclass, jobject, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     com_planet_light2345_seclib_SecService
 * Method:    decrypt2
 * Description: 解密，输入content、key参数1、key参数2，p1 + normalKey + p2作为key，md5后作为key，再和内容一起解密
 * Signature: (Landroid/content/Context;[B[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_planet_light2345_seclib_SecService_decrypt2
    (JNIEnv *, jclass, jobject, jbyteArray, jbyteArray, jbyteArray);

jbyteArray encrypt
    (JNIEnv * env, jclass clazz, jobject context, jbyteArray content, jbyteArray key, int md5);

char * salt_b64_encode(const char * content, char * salt);

char * salt_b64_encode_nomd5(const char * content, char * salt);

jbyteArray decode(JNIEnv * env, const char *native_string, const char * native_string_key, long key_len);

jbyteArray decodeWidthMd5(JNIEnv * env, const char *native_string, const char * native_string_key);

jbyteArray encrypt2(JNIEnv * env, jclass clazz, jobject context, jbyteArray content, const char * key, int md5);

char * joinChar(char *s1, char *s2);

#ifdef __cplusplus
}
#endif
#endif
